# Copyright 2023 The Authors (see AUTHORS file)

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#      http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Adding a note for AOD requests.
name: 'aod-note'

on:
  workflow_call:
    inputs:
      expiry_hours:
        description: 'The number of hours an AOD PR should be expired since last updated.'
        type: 'number'
        required: true
      aod_instruction_link:
        description: 'The link to your AOD instructions. Default is the repo root.'
        type: 'string'
        required: false
        default: '${{ github.server_url }}/${{ github.repository }}'

env:
  AOD_NOTE: >
    ⛔️ <strong>This is an AOD request, and merging is NOT allowed.</strong>
    The request will be automatically applied once the code owners approve it.
    Please close the PR once you are finished or it will automatically be closed
    after ~${{ inputs.expiry_hours }} hours of it's last commit. Please
    <strong>DO NOT</strong> delete the branch manually, the branch will be
    automatically deleted once PR is closed. For more instructions, please see
    [here](${{ inputs.aod_instruction_link }}).
  AOD_BREAKGLASS_NOTE: >
    🚨 <strong>This request will be automatically applied since it has been labeled as aod-breakglass</strong>.

jobs:
  note:
    runs-on: 'ubuntu-latest'
    permissions:
      pull-requests: 'write'
    name: 'Add AOD Note'
    steps:
      - name: 'Add AOD Note'
        if: |-
          github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # ratchet:actions/github-script@v7
        with:
          github-token: '${{ github.token }}'
          retries: '3'
          script: |+
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              body: `${{ env.AOD_NOTE }}`,
            });

      - name: 'Add AOD Breakglass Note'
        if: |-
          contains(github.event.pull_request.labels.*.name, 'aod-breakglass')
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # ratchet:actions/github-script@v7
        with:
          github-token: '${{ github.token }}'
          retries: '3'
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              body: `${{ env.AOD_BREAKGLASS_NOTE }}`,
            });
